#!/bin/bash
echo "=== Server Information ==="
echo "Hostname: $(hostname)"
echo "IP Address: $(hostname -I | awk '{print $1}')"
echo "Uptime: $(uptime -p)"
echo ""
echo "=== Service Status ==="
echo "Nginx (System): $(systemctl is-active nginx)"
echo "Docker: $(systemctl is-active docker)"
echo "UFW Firewall: $(systemctl is-active ufw)"
echo "WireGuard: $(systemctl is-active wg-quick@wg0 || echo 'Not configured')"
echo ""
echo "=== Access URLs ==="
echo "Web Server (static): http://$(hostname -I | awk '{print $1}')"
echo "Portainer: https://$(hostname -I | awk '{print $1}'):9443"
echo "Health Check: http://$(hostname -I | awk '{print $1}')/health"
echo ""
echo "=== Hybrid Nginx Setup ==="
echo "• System Nginx handles ports 80/443 and SSL"
echo "• Docker containers run on internal ports (8080+)"
echo "• Project configs in: /etc/nginx/sites-projects/"
echo "• Template file: /etc/nginx/sites-projects/project-template.conf"
echo ""
echo "=== Docker Containers ==="
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
